name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install --legacy-peer-deps
        
      - name: Build project
        run: npm run build
        
      - name: Check for large files that might cause upload issues
        run: |
          echo "=== Files larger than 25MB ==="
          find dist -type f -size +25M -exec ls -lh {} \; || echo "No large files found"
        
      - name: Verify build output
        run: |
          echo "Contents of dist directory:"
          ls -la dist/
          echo "Contents of dist/images:"
          ls -la dist/images/ || echo "No images directory"
          echo "Contents of dist/content:"
          ls -la dist/content/ || echo "No content directory"
        
      - name: List dist contents for debugging
        run: |
          echo "=== Contents of dist directory ==="
          find dist -type f -exec ls -lh {} \;
          echo "=== Directory structure ==="
          tree dist || ls -la dist/
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Create tarball manually (workaround for missing directories)
        run: |
          cd dist
          tar -czf ../pages.tar.gz .
          cd ..
          ls -la pages.tar.gz
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4